### ISSUE TITLE
Example for nested frontmatter

### ISSUE THREAD

**Issue by mkhnpr** [cosmic-horse/cosmic_frontmatter#1]
Hey @PaulHalliday , thanks for the amazing library. Great job!

How to serialize nested frontmatter, with freezed?

I tried to do as discussed here with no luck:
https://github.com/rrousselGit/freezed/issues/86#issuecomment-957956629

Error I get is :
`type 'YamlMap' is not a subtype of type 'Map<String, dynamic>' in type cast,`

An example how to serialize and access nested frontmatter would be a huge help! 

I am trying to parse a frontmatter like this, place is being returned as `YamlMap` instead of `Map<String,dynamic>`

```md
---
name: "foobar"
date: 1990-09-01
place:
  birth: "London"
  death: "Paris"
---
```

**Comment by PaulHalliday** [comment]
Sorry I missed this @mkhnpr!

Glad you've sorted it though!
